node{
   stage("Git Clone"){

        git branch: 'master', url: 'https://github.com/jsilaparasetti/jenkinsfile-1.git'
    }
   
    stage("Docker build"){
    bat 'docker build -t jsilaparasetti/app-2-img:latest .'
        bat 'docker image ls'
    }

    withCredentials([string(credentialsId: 'ineeladri', variable: 'PASSWORD')]) {
        bat 'docker login -u ineeladri -p $PASSWORD'
    }

    stage("Pushing Image to Docker Hub"){
     
      bat 'docker push ineeladri/app-2-img:latest'
       }
    post {
        always {
            script {
                if (getContext(hudson.FilePath)) {
                    deleteDir()
                }
            }
        }
    }
}
