pipeline{
    agent any
    environment{
        dockerImage =''
        registry ='ineeladri/test2'
        registryCredential ='indudockerhub' 
    }
    stages{
        stage('Checkout'){
            steps{
               checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/jsilaparasetti/jenkinsfile-1.git']]])
            }
        }
        stage('Build Docker image'){
            steps{
                script{
                    dockerImage = docker.build registry
                }
            }
        }
        
        // Uploading Docker images into Docker Hub
    stage('Upload Image') {
     steps{    
         script {
            docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
            }
        }
      }
    }
        
    }
}
